### ISSUE TITLE
v1.1 Roadmap

### ISSUE THREAD

**Issue by jeroenptrs** [be-neo/neoblog#41]
This includes changes **that will not require a new smart contract**
## Increasing Application functionality / Must haves
- [ ] Apply changes laid out in #33
- [ ] Rewrite service worker to properly cache and upgrade itself
- [ ] Cache content client side
- [ ] Extrapolate non-Neoblog-specific Neon-js wrappers to separate package(s) for third party adoption
- [ ] Validation on submitting a post. No markdown tags allowed in title + category may not be null
- [ ] Research and update state mgmt: MobX vs Redux
## Increasing IPFS functionality / Should haves
- [ ] Master IPFS docs and document best possible scenarios
- [ ] Save forthcoming articles in the same repo
- [ ] Move to Infura node and gateway for future content
## Experimental / Could haves
- [ ] Cache requests via FaaS using Service Worker and Webtask
- [ ] Google AMP integration
- [ ] Prerender articles for SEO (prerender.io)

**Comment by jeroenptrs** [comment]
Moved state MGMT from #43 to here

**Comment by jeroenptrs** [comment]
Added Infura support TODO: https://blog.infura.io/getting-started-with-infura-28e41844cc89
