### ISSUE TITLE
v2.0 roadmap

### ISSUE THREAD

**Issue by DalderupMaurice** [be-neo/neoblog#43]
These changes **will** enhance the smart contract. Redeployment is **required**.

## Increasing Smart contract functionality / Must haves
- [ ] Initial seed list of categories enforced by the SC. 
- [ ] Ability to add categories (strict rules, only creators or public vote?)
- [ ] Ability to update an existing post

## Enchance / Should haves
- [ ] None so far. We are open for suggestions

## Experimental / Could haves
- [ ] None so far. We are open for suggestions

**NOTE** this is not the final state of the v2.0 roadmap. Check back regularly to discover new features!
If there's a cool feature you'd like to see, do not hesitate to leave a comment 💯

**Comment by jeroenptrs** [comment]
State Management should go in #41 since it's intertwined with routing 😄
